---
kind: Config
apiVersion: v1
preferences: {}
clusters:
- name: gcp-cluster-1
  cluster:
    server: API ENDPOINT # change with the kubernetes API server URL for access 
    insecure-skip-tls-verify: true
users:
- name: user 
  user:
    token: TOKEN #replace it with the output of step 2 
contexts:
- name: cluster-1
  context:
    cluster: gcp-cluster-1
    user: user
current-context: user@cluster-1

